use std::sync::mpsc::SyncSender;
use std::sync::Arc;
use std::sync::OnceLock;
use std::thread;
use std::thread::JoinHandle;

use windows::Win32::Foundation::*;
use windows::Win32::System::Threading::GetCurrentThreadId;
use windows::Win32::UI::WindowsAndMessaging::*;
use windows::Win32::UI::Input::KeyboardAndMouse::GetKeyState;

use crate::actions::MappingTable;
use crate::state::{HookContext, HookEvent};

static CTX: OnceLock<Arc<HookContext>> = OnceLock::new();

unsafe extern "system" fn keyboard_hook_proc(ncode: i32, wparam: WPARAM, lparam: LPARAM) -> LRESULT {
    if ncode < 0 {
        return unsafe { CallNextHookEx(None, ncode, wparam, lparam) };
    }

    let kb = unsafe { &*(lparam.0 as *const KBDLLHOOKSTRUCT) };

    // Skip injected events (generated by our own enigo via SendInput)
    if (kb.flags.0 & 0x10) != 0 {
        return unsafe { CallNextHookEx(None, ncode, wparam, lparam) };
    }

    if let Some(ctx) = CTX.get() {
        let is_press = wparam.0 == WM_KEYDOWN as usize || wparam.0 == WM_SYSKEYDOWN as usize;
        let is_release = wparam.0 == WM_KEYUP as usize || wparam.0 == WM_SYSKEYUP as usize;

        if is_press || is_release {
            let capslock_now = unsafe { (GetKeyState(0x14) & 1) as i32 };
            let event = ctx.process_key(kb.vkCode, is_press, capslock_now, 0);

            match &event {
                HookEvent::PassThrough => {}
                HookEvent::Block => return LRESULT(1),
                HookEvent::Action(_) | HookEvent::ToggleCapsLock => {
                    ctx.send_event(event);
                    return LRESULT(1);
                }
            }
        }
    }

    unsafe { CallNextHookEx(None, ncode, wparam, lparam) }
}

pub struct HookThread {
    handle: JoinHandle<()>,
    thread_id: u32,
}

impl HookThread {
    pub fn stop(self) {
        unsafe {
            let _ = PostThreadMessageW(self.thread_id, WM_QUIT, WPARAM(0), LPARAM(0));
        }
        let _ = self.handle.join();
    }
}

pub fn run_hook_thread(
    sender: SyncSender<HookEvent>,
    mapping: MappingTable,
    hold_threshold_ms: u64,
    tap_to_toggle: bool,
) -> HookThread {
    let (ready_tx, ready_rx) = std::sync::mpsc::channel();

    let handle = thread::spawn(move || {
        let thread_id = unsafe { GetCurrentThreadId() };
        ready_tx.send(thread_id).ok();

        let ctx = Arc::new(HookContext::new(sender, mapping, hold_threshold_ms, tap_to_toggle));

        CTX.set(ctx.clone()).ok();

        let hook = unsafe {
            SetWindowsHookExW(
                WH_KEYBOARD_LL,
                Some(keyboard_hook_proc),
                None,
                0,
            )
        };

        match hook {
            Ok(hook) => {
                
                let mut msg = MSG::default();
                loop {
                    let ret = unsafe { GetMessageW(&mut msg, None, 0, 0) };
                    if ret.0 <= 0 {
                        break;
                    }
                }

                unsafe {
                    let _ = UnhookWindowsHookEx(hook);
                }
            }
            Err(_) => {
                            }
        }

            });

    let thread_id = ready_rx.recv().expect("Hook thread should start");
    HookThread { handle, thread_id }
}

pub fn update_hook_settings(hold_threshold_ms: u64, tap_to_toggle: bool, mapping: MappingTable) {
    if let Some(ctx) = CTX.get() {
        ctx.update_settings(hold_threshold_ms, tap_to_toggle, mapping);
    }
}
